[ADD] Reservation, ReservationDao, ReservationDaoImpl
VaclavStebra/pa165-booking-manager pull request #18
Opened 2016-10-25 17:40 UTC by pthutta

2016-10-25 18:09 UTC, vasekstebra requested changes
Please see comments inline. Also please add annotation @Column(nullable=false) for all attributes that have NotNull annotation as per seminar discussion. Good job (y)

2016-10-25 18:09 UTC, VaclavStebra commented on BookingManager-persistence/src/main/java/cz/muni/fi/pa165/brown/entity/Reservation.java
> +    private Date from;
Add annotation Temporal(TemporalType.TIMESTAMP)

2016-10-25 18:09 UTC, VaclavStebra commented on BookingManager-persistence/src/main/java/cz/muni/fi/pa165/brown/entity/Reservation.java
> +    private Date to;
Same annotation as for from attribute

2016-10-25 20:21 UTC, Dominick1993 commented
Just a side note, wouldn't it be better if used something like `java.sql.Timestamp` instead of 'java.util.Date' for the purpose of storing the date?

2016-10-25 20:53 UTC, VaclavStebra commented
@Dominick1993 In the seminar tasks was used `java.util.Date` with the Temporal annotation to fine tune it to the database datatype. From what I was able to find I didn't find much difference between using either `java.sql.Timestamp` and `java.util.Date` with the `@Temporal(TemporalType.TIMESTAMP)` annotation for a simple project. But according to [this article](http://www.developerscrappad.com/228/java/java-ee/ejb3-jpa-dealing-with-date-time-and-timestamp/) there could be some problems when persisting and retrieving `java.sql.Timestamp` and converting it to `java.util.Date` to use it in the bussines code of the application. So I guess the safest way is to stick with` java.util.Date` and the Temporal annotation.

2016-10-25 22:31 UTC, Dominick1993 commented on BookingManager-persistence/src/main/java/cz/muni/fi/pa165/brown/entity/Reservation.java
> +    private Date from;
Please change the name of this field to something which does not match sql keyword exactly (e.g. reservedFrom). While I was implementing the tests I found out that "from" field name caused trouble in SQL statements that hibernate produces, which has caused the `org.hibernate.exception.SQLGrammarException`

2016-10-25 22:53 UTC, Dominick1993 commented on BookingManager-persistence/src/main/java/cz/muni/fi/pa165/brown/entity/Reservation.java
> +    }
I'd suggest not to compare the reservations by `id`, please adjust the `equals()` and `hashCode()` methods accordingly. I made the same (possible) mistake in my implementation of `Room` entity.

2016-10-29 14:54 UTC, pthutta commented
@VaclavStebra Alright, all issues should be fixed now. Thanks for pointing them out.

2016-10-29 15:09 UTC, VaclavStebra commented
Thanks! It looks good.

2016-10-29 15:09 UTC, vasekstebra approved these changes

2016-10-29 15:09 UTC, merged